[29/May/2020 09:12:46] ERROR [django.request:132] Internal Server Error: /
Traceback (most recent call last):
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sanjar/Documents/libercen/users/views.py", line 22, in home
    return render(request, 'basic/welcome.html')
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/templatetags/static.py", line 105, in render
    url = self.url(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/templatetags/static.py", line 102, in url
    return self.handle_simple(path)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'icons/logo-big.png'
[29/May/2020 09:12:46] ERROR [django.server:124] "GET / HTTP/1.1" 500 27
[29/May/2020 09:12:53] ERROR [django.request:132] Internal Server Error: /
Traceback (most recent call last):
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sanjar/Documents/libercen/users/views.py", line 22, in home
    return render(request, 'basic/welcome.html')
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/templatetags/static.py", line 105, in render
    url = self.url(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/templatetags/static.py", line 102, in url
    return self.handle_simple(path)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'icons/logo-big.png'
[29/May/2020 09:12:53] ERROR [django.server:124] "GET / HTTP/1.1" 500 27
[29/May/2020 09:12:53] ERROR [django.request:132] Internal Server Error: /
Traceback (most recent call last):
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sanjar/Documents/libercen/users/views.py", line 22, in home
    return render(request, 'basic/welcome.html')
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/templatetags/static.py", line 105, in render
    url = self.url(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/templatetags/static.py", line 102, in url
    return self.handle_simple(path)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'icons/logo-big.png'
[29/May/2020 09:12:53] ERROR [django.server:124] "GET / HTTP/1.1" 500 27
[29/May/2020 09:12:54] ERROR [django.request:132] Internal Server Error: /
Traceback (most recent call last):
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sanjar/Documents/libercen/users/views.py", line 22, in home
    return render(request, 'basic/welcome.html')
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/templatetags/static.py", line 105, in render
    url = self.url(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/templatetags/static.py", line 102, in url
    return self.handle_simple(path)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'icons/logo-big.png'
[29/May/2020 09:12:54] ERROR [django.server:124] "GET / HTTP/1.1" 500 27
[29/May/2020 09:12:54] ERROR [django.request:132] Internal Server Error: /
Traceback (most recent call last):
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sanjar/Documents/libercen/users/views.py", line 22, in home
    return render(request, 'basic/welcome.html')
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/templatetags/static.py", line 105, in render
    url = self.url(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/templatetags/static.py", line 102, in url
    return self.handle_simple(path)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'icons/logo-big.png'
[29/May/2020 09:12:54] ERROR [django.server:124] "GET / HTTP/1.1" 500 27
[29/May/2020 09:13:25] ERROR [django.request:132] Internal Server Error: /
Traceback (most recent call last):
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sanjar/Documents/libercen/users/views.py", line 22, in home
    return render(request, 'basic/welcome.html')
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/templatetags/static.py", line 105, in render
    url = self.url(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/templatetags/static.py", line 102, in url
    return self.handle_simple(path)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'icons/logo-big.png'
[29/May/2020 09:13:25] ERROR [django.server:124] "GET / HTTP/1.1" 500 27
[29/May/2020 09:19:00] ERROR [django.request:132] Internal Server Error: /
Traceback (most recent call last):
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sanjar/Documents/libercen/users/views.py", line 22, in home
    return render(request, 'basic/welcome.html')
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/templatetags/static.py", line 105, in render
    url = self.url(context)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/templatetags/static.py", line 102, in url
    return self.handle_simple(path)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "/home/sanjar/anaconda3/envs/lenv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'icons/logo-big.png'
[29/May/2020 09:19:00] ERROR [django.server:124] "GET / HTTP/1.1" 500 27
